ALTER TABLE pet_history ADD COLUMN weight TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN temp TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN hr TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN exam TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN diagnosis TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN nextControl TEXT NOT NULL DEFAULT '';
