ALTER TABLE appointments ADD COLUMN vetUserId TEXT NOT NULL DEFAULT '';
ALTER TABLE groomingAppointments ADD COLUMN groomerUserId TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_history ADD COLUMN vetUserId TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_vaccines ADD COLUMN vetUserId TEXT NOT NULL DEFAULT '';
ALTER TABLE pet_dewormings ADD COLUMN vetUserId TEXT NOT NULL DEFAULT '';
